force-app/main/default/objects/Open_Weather_API_Key__mdt/Open_Weather_API_Key__mdt.object-meta.xml
<CustomObject>
    <label>Open Weather API Key</label>
    <pluralLabel>Open Weather API Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Open_Weather_API_Key__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Open_Weather_API_Key__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WeatherCallout.cls
/**
 * Created by oleksiitromsa on 25.01.2021.
 */

public class WeatherCallout {

    public static Weather__c makeGetCallout(String city) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        Open_Weather_API_Key__mdt apiKey = [SELECT Key__c FROM Open_Weather_API_Key__mdt WHERE Is_Active__c = true];
        String endPoint = 'http://api.openweathermap.org/data/2.5/weather?q=' + city
                + '&appid=' + apiKey.Key__c;
        request.setEndpoint(endPoint);
        HttpResponse response = http.send(request);

        if (response.getStatusCode() != 200) {
            throw new CalloutException('No forecast for city ' + city);
        }

        WeatherDto dto = (WeatherDto) JSON.deserialize(response.getBody(), WeatherDto.class);
        Weather__c weather = WeatherMapper.dtoToWeather(dto);
        insert weather;
        return weather;
    }
}