force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Clouds_All__c.field-meta.xml
<CustomField>
    <fullName>Clouds_All__c</fullName>
    <label>Clouds All</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Cod__c.field-meta.xml
<CustomField>
    <fullName>Cod__c</fullName>
    <label>Cod</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Feels_Like__c</fullName>
    <label>Feels Like</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/longitude__c.field-meta.xml
<CustomField>
    <fullName>longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Sunrize__c.field-meta.xml
<CustomField>
    <fullName>Sunrize__c</fullName>
    <label>Sunrize</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Sunset__c.field-meta.xml
<CustomField>
    <fullName>Sunset__c</fullName>
    <label>Sunset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Sys_Country__c.field-meta.xml
<CustomField>
    <fullName>Sys_Country__c</fullName>
    <label>Sys Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Sys_Id__c.field-meta.xml
<CustomField>
    <fullName>Sys_Id__c</fullName>
    <label>Sys Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Sys_Type__c.field-meta.xml
<CustomField>
    <fullName>Sys_Type__c</fullName>
    <label>Sys Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temp_Max__c.field-meta.xml
<CustomField>
    <fullName>Temp_Max__c</fullName>
    <label>Temp Max</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temp_Min__c.field-meta.xml
<CustomField>
    <fullName>Temp_Min__c</fullName>
    <label>Temp Min</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Weather_Icon__c.field-meta.xml
<CustomField>
    <fullName>Weather_Icon__c</fullName>
    <label>Weather Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Weather_Id__c.field-meta.xml
<CustomField>
    <fullName>Weather_Id__c</fullName>
    <label>Weather Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Weather_Main__c.field-meta.xml
<CustomField>
    <fullName>Weather_Main__c</fullName>
    <label>Weather Main</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Wind_Deg__c.field-meta.xml
<CustomField>
    <fullName>Wind_Deg__c</fullName>
    <label>Wind Deg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeatherMapper.cls
/**
 * Created by oleksiitromsa on 25.01.2021.
 */

public with sharing class WeatherMapper {
    public static Weather__c dtoToWeather(WeatherDto dto) {
        Weather__c weather = new Weather__c();

        if (dto.coord != null) {
            weather.Latitude__c = dto.coord.lat;
            weather.longitude__c = dto.coord.lon;
        }
        if (dto.weather != null) {
            weather.Weather_Id__c = dto.weather.get(0).id;
            weather.Weather_Main__c = dto.weather.get(0).main;
            weather.Weather_Description__c = dto.weather.get(0).description;
            weather.Weather_Icon__c = dto.weather.get(0).icon;
        }
        if (dto.main != null) {
            weather.Temperature__c = dto.main.temp;
            weather.Feels_Like__c = dto.main.feels_like;
            weather.Temp_Max__c = dto.main.temp_max;
            weather.Temp_Min__c = dto.main.temp_min;
            weather.Pressure__c = dto.main.pressure;
            weather.Humidity__c = dto.main.humidity;
        }
        if (dto.wind != null) {
            weather.Wind_Speed__c = dto.wind.speed;
            weather.Wind_Deg__c = dto.wind.deg;
        }
        if (dto.clouds != null) {
            weather.Clouds_All__c = dto.clouds.all;
        }
        if (dto.dt != null) {
            weather.Datetime__c = Datetime.newInstance(dto.dt * 1000);
        }
        if (dto.sys != null) {
            weather.Sys_Type__c = dto.sys.type;
            weather.Sys_Id__c = dto.sys.id;
            weather.Sys_Country__c = dto.sys.country;
            if (dto.sys.sunrise != null) {
                weather.Sunrize__c = Datetime.newInstance(dto.sys.sunrise * 1000);
            }
            if (dto.sys.sunset != null) {
                weather.Sunset__c = Datetime.newInstance(dto.sys.sunset * 1000);
            }
        }
        weather.Base__c = dto.base;
        weather.Visibility__c = dto.visibility;
        weather.Timezone__c = dto.timezone;
        weather.External_Id__c = dto.id;
        weather.City_Name__c = dto.name;
        weather.Cod__c = dto.cod;

        return weather;
    }
}